remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [TROVE ZERO]
description: [TROVEZERO is a interest Manager]
show_downloads: ["false"]
